#!/bin/sh
echo
cd aclocal
ln -sf /usr/share/aclocal/codeset.m4   .
ln -sf /usr/share/aclocal/gettext.m4   .
ln -sf /usr/share/aclocal/glibc21.m4   .
ln -sf /usr/share/aclocal/iconv.m4   .
ln -sf /usr/share/aclocal/isc-posix.m4   .
ln -sf /usr/share/aclocal/lcmessage.m4  .
ln -sf /usr/share/aclocal/progtest.m4  .
cd ..
touch README
aclocal --version
aclocal -I aclocal
echo "####"
gettextize -c -f --intl
cp /usr/share/gettext/gettext.h src/libgettext.h
aclocal -I m4
echo "####"
autoheader --version
autoheader
echo "####"
automake --version
automake --add-missing
rm README
echo "####"
autoconf --version
autoconf
./configure --enable-maintainer-mode
